### ISSUE TITLE
Different if style

### ISSUE THREAD

**Issue by evancz** [ohanhi/elm-style-guide#2]
I just ran into this repo on twitter, and it's really good! Not sure when I can get around to it, but I think it makes sense to include a large fraction of this in the style guide.

In any case, I wanted to suggest changing the `if` style to be like this:

``` elm
-- ✅ GOOD
if needleInHaystack then
  actAccordingly
else
  doNothing

-- ❌ BAD
if needleInHaystack
  then actAccordingly
  else doNothing

-- ❌ BAD
if needleInHaystack then actAccordingly else doNothing
```

This is nice because it makes it super simple to start chaining `if` expressions:

``` elm
-- ✅ GOOD
if needleInHaystack then
  actAccordingly
else if whatever then
  doSomethingElse
else
  doNothing
```

It also "looks more familiar" but I think that's more a function of the fact that C-like languages have had a very long time to standardize on patterns that have good "code texture" and grow nicely as you write more code. So I think the similarity is more an observation about the structure of `if` expressions over time.

**Comment by ohanhi** [comment]
This is now (finally) part of the style guide. Thanks for pointing this out! :+1:
